# Generated by Django 5.0.1 on 2024-02-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_alter_snippet_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
