# Generated by Django 5.0.1 on 2024-02-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0004_snippet_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
