# Generated by Django 5.0.1 on 2024-02-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0005_alter_snippet_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
